### ISSUE TITLE
The command parameter syntax is not valid

### ISSUE THREAD

**Issue by BCEM** [moozzyk/CodeFirstFunctions#19]
Hi there! I have a strange issue with my TVF it throws System.Data.Entity.Core.EntitySqlException: The command parameter syntax '@_project_id' is not valid.

Setup is exactly the same as in "readme".
Method:

```
[DbFunction("TestContext", "get_project_items")]
public IQueryable<get_project_items_Result> get_project_items(int projectId, bool dry)
{
    var projectIdParameter = new ObjectParameter("_project_id", typeof(int)) { Value = projectId };
    var dryParameter = new ObjectParameter("_dry", typeof(bool)) { Value = dry };

    var results = (this as IObjectContextAdapter).ObjectContext
        .CreateQuery<get_project_items_Result>(
            string.Format("[{0}].{1}", GetType().Name, "[get_project_items](@_project_id, @_dry)"), projectIdParameter, dryParameter);

    return results;
}
```
Function exists and parameters are the same.

I've tried to register get_project_items_Result as an Entity and as a ComplexType - the same results.

By looking at stack trace I even can't find that CodeFirstFunctions where used:
```
   at System.Data.Entity.Core.Common.EntitySql.AST.QueryParameter..ctor(String parameterName, String query, Int32 inputPos)
   at System.Data.Entity.Core.Common.EntitySql.CqlLexer.NewParameterToken(String param)
   at System.Data.Entity.Core.Common.EntitySql.CqlLexer.Accept_11()
   at System.Data.Entity.Core.Common.EntitySql.CqlLexer.yylex()
   at System.Data.Entity.Core.Common.EntitySql.CqlParser.yylex()
   at System.Data.Entity.Core.Common.EntitySql.CqlParser.yyparse()
   at System.Data.Entity.Core.Common.EntitySql.CqlParser.internalParseEntryPoint()
   at System.Data.Entity.Core.Common.EntitySql.CqlParser.Parse(String query)
   at System.Data.Entity.Core.Common.EntitySql.CqlQuery.Parse(String commandText, ParserOptions parserOptions)
   at System.Data.Entity.Core.Common.EntitySql.CqlQuery.CompileCommon[TResult](String commandText, ParserOptions parserOptions, Func`3 compilationFunction)
   at System.Data.Entity.Core.Common.EntitySql.CqlQuery.CompileQueryCommandLambda(String queryCommandText, Perspective perspective, ParserOptions parserOptions, IEnumerable`1 parameters, IEnumerable`1 variables)
   at System.Data.Entity.Core.Objects.EntitySqlQueryState.Parse()
   at System.Data.Entity.Core.Objects.EntitySqlQueryState.GetExecutionPlan(Nullable`1 forMergeOption)
   at System.Data.Entity.Core.Objects.ObjectQuery`1.<>c__DisplayClass7.<GetResults>b__6()
   at System.Data.Entity.Core.Objects.ObjectContext.ExecuteInTransaction[T](Func`1 func, IDbExecutionStrategy executionStrategy, Boolean startLocalTransaction, Boolean releaseConnectionOnSuccess)
   at System.Data.Entity.Core.Objects.ObjectQuery`1.<>c__DisplayClass7.<GetResults>b__5()
   at System.Data.Entity.SqlServer.DefaultSqlExecutionStrategy.Execute[TResult](Func`1 operation)
   at System.Data.Entity.Core.Objects.ObjectQuery`1.GetResults(Nullable`1 forMergeOption)
   at System.Data.Entity.Core.Objects.ObjectQuery`1.<System.Collections.Generic.IEnumerable<T>.GetEnumerator>b__0()
   at System.Data.Entity.Internal.LazyEnumerator`1.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at TestApp.Core.BLL.Services.ProjectService.GetProjectById(Int32 project_id, Boolean dry) 103
   at System.Runtime.Remoting.Messaging.Message.Dispatch(Object target)
   at System.Runtime.Remoting.Messaging.StackBuilderSink.SyncProcessMessage(IMessage msg)
```

**Comment by moozzyk** [comment]
Looks like EF does not allow `_` as the first character in the parameter name. The exception is being thrown from here:

https://github.com/aspnet/EntityFramework6/blob/087bd198bfdc4175fad2565ddaa282ca66fed699/src/EntityFramework/Core/Common/EntitySql/AST/QueryParameter.cs#L25-L33

I guess you will need to rename your parameter.

I am closing this issue because there is nothing that can be done in CodeFristFunctions - the limitation comes from EF itself.

**Comment by BCEM** [comment]
Yep, renaming of parameters did the trick. Thank you!

**Comment by moozzyk** [comment]
:+1:
