### ISSUE TITLE
EF6 TVF for one column result

### ISSUE THREAD

**Issue by ghost** [moozzyk/CodeFirstFunctions#26]
Hello,

Your project is good! Thanks a lot. It works for me if I have an EF entity returned from TVF.

I decided to try to create TVF that returns only one column (UNIQUEIDENTIFIER). So I declared this in C#:

```
        [DbFunction("dbo", "SearchQuotes")]
        public IQueryable<Guid> SearchQuotes(string search)
        {
            var parameter = search != null 
               ? new ObjectParameter("search", search)
               : new ObjectParameter("search", typeof(string));

            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<Guid>(
               $"[{GetType().Name}].[SearchQuotes](@search)", parameter);
        }
```

I also have:
```
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            modelBuilder.Conventions.Add(new FunctionsConvention<CoreContext>("dbo"));
        }
```

But Add-Migration reported an exception:
```
PM> Add-Migration Aaaaa
System.ArgumentException: The argument 'name' cannot be null, empty or contain only white space.
   at System.Data.Entity.Utilities.Check.NotEmpty(String value, String parameterName)
   at System.Data.Entity.Core.Metadata.Edm.EdmProperty.Create(String name, TypeUsage typeUsage)
   at CodeFirstStoreFunctions.StoreFunctionBuilder.CreateReturnRowType(String propertyName, EdmType edmType)
   at CodeFirstStoreFunctions.StoreFunctionBuilder.CreateFunctionReturnParameters(FunctionDescriptor functionDescriptor)
   at CodeFirstStoreFunctions.StoreFunctionBuilder.Create(FunctionDescriptor functionDescriptor)
   at CodeFirstStoreFunctions.FunctionsConvention.Apply(EntityContainer item, DbModel model)
   at System.Data.Entity.ModelConfiguration.Configuration.ConventionsConfiguration.ModelConventionDispatcher.Dispatch[T](T item)
   at System.Data.Entity.ModelConfiguration.Configuration.ConventionsConfiguration.ModelConventionDispatcher.VisitEdmEntityContainer(EntityContainer item)
   at System.Data.Entity.Edm.EdmModelVisitor.VisitCollection[T](IEnumerable`1 collection, Action`1 visitMethod)
   at System.Data.Entity.Edm.EdmModelVisitor.VisitEntityContainers(IEnumerable`1 entityContainers)
   at System.Data.Entity.Edm.EdmModelVisitor.VisitEdmModel(EdmModel item)
   at System.Data.Entity.ModelConfiguration.Configuration.ConventionsConfiguration.ModelConventionDispatcher.VisitEdmModel(EdmModel item)
   at System.Data.Entity.ModelConfiguration.Configuration.ConventionsConfiguration.ModelConventionDispatcher.Dispatch()
   at System.Data.Entity.ModelConfiguration.Configuration.ConventionsConfiguration.ApplyStoreModel(DbModel model)
   at System.Data.Entity.DbModelBuilder.Build(DbProviderManifest providerManifest, DbProviderInfo providerInfo)
   at System.Data.Entity.DbModelBuilder.Build(DbConnection providerConnection)
   at System.Data.Entity.Internal.LazyInternalContext.CreateModel(LazyInternalContext internalContext)
   at System.Data.Entity.Internal.RetryLazy`2.GetValue(TInput input)
   at System.Data.Entity.Internal.LazyInternalContext.InitializeContext()
   at System.Data.Entity.Internal.LazyInternalContext.get_ModelBeingInitialized()
   at System.Data.Entity.Infrastructure.EdmxWriter.WriteEdmx(DbContext context, XmlWriter writer)
   at System.Data.Entity.Utilities.DbContextExtensions.<>c__DisplayClass1.<GetModel>b__0(XmlWriter w)
   at System.Data.Entity.Utilities.DbContextExtensions.GetModel(Action`1 writeXml)
   at System.Data.Entity.Utilities.DbContextExtensions.GetModel(DbContext context)
   at System.Data.Entity.Migrations.DbMigrator..ctor(DbMigrationsConfiguration configuration, DbContext usersContext, DatabaseExistenceState existenceState, Boolean calledByCreateDatabase)
   at System.Data.Entity.Migrations.DbMigrator..ctor(DbMigrationsConfiguration configuration)
   at System.Data.Entity.Migrations.Design.MigrationScaffolder..ctor(DbMigrationsConfiguration migrationsConfiguration)
   at System.Data.Entity.Migrations.Design.ToolingFacade.ScaffoldRunner.RunCore()
   at System.Data.Entity.Migrations.Design.ToolingFacade.BaseRunner.Run()
```

We use EF6.2, .Net4.7.1, VS2017

I have workaround but I thought it might be interesting for you.

Thanks again!

--
Sergiy

**Comment by moozzyk** [comment]
I think the issue here is that because GUID is an EF primitive type we don't have a mapping between the name of the column returned by the TVF and the result type. AFAIR you can use the `DbFunctionDetails` attribute to define such a mapping. End to end tests contain some examples - for instance in this case: 
https://github.com/moozzyk/CodeFirstFunctions/blob/d1a1c27270c6e5637b1a03fdb80e05e432aee8fb/CodeFirstStoreFunctionsTests/E2ETests.cs#L70-L77
the TVF returns a byte column (byte, similarly to GUID, is an EF primitive type) and the `DbFunctionDetails` attribute defines the name of column to use. 

Let me know if this helps.

**Comment by ghost** [comment]
Pawel,

Thanks a lot! I had to read your E2ETests.cs better.
You are right. I added [DbFunctionDetails(ResultColumnName = "Id")] and it is working now.

Thanks again!

--
Sergiy

**Comment by moozzyk** [comment]
I am glad that you were able to make it work. I wish the exception thrown in this case was more clear.
